name: Sync Image to Aliyun

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: chuang2871@aliyun.com
        password: Lc123456
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo copy docker://docker.io/redis:7.2.4 docker://registry.cn-hangzhou.aliyuncs.com/chexuetang/redis:7.2.4
#        skopeo copy docker://docker.io/infiniflow/ragflow:dev docker://registry.cn-hangzhou.aliyuncs.com/chexuetang/ragflow:dev
#        skopeo copy docker://docker.elastic.co/elasticsearch/elasticsearch:8.11.3 docker://registry.cn-hangzhou.aliyuncs.com/chexuetang/elasticsearch:8.11.3
#        skopeo copy docker://docker.io/freeren/qanything:v1.2.2 docker://registry.cn-hangzhou.aliyuncs.com/chexuetang/qanything:v1.2.2
